# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# NB
# - can't have a : in a value, e.g. the title
title: FT Labs Experimental Crosswords
email: ftlabs@ft.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to our new, experimental crosswords, which can be filled in online.
baseurl: "/crosswords" # for local builds only, is ignored by GH Pages
url: "http://labs.ft.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ftlabs
github_username:  railsagainstignorance
original_crosswords_site_url: https://www.ft.com/crossword

feedback_url: http://labs.ft.com/about

google_analytics: UA-72191230-3

# Build settings
o_crossword_version: ^1.6.1 # updated to ensure we don't have the old version cached anywhere
markdown: kramdown
theme: minima
gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _scripts

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "crossword"

webrick:
  headers:
    Cache-Control: 60 # keep short for dev
